# 테마 설정: 사이드바가 있는 Just the Docs 테마를 계속 활용
remote_theme: just-the-docs/just-the-docs

# 검색 기능 켜기 (선택사항)
search_enabled: true

# ★★★ 여기가 마법의 핵심 ★★★
# 특정 폴더의 파일에 기본값을 강제로 적용
defaults:
  - scope:
      path: "posts"  # 'posts' 폴더에 있는 모든 파일에 대하여
    values:
      layout: "default" # 머리말(---)이 없어도 'default' 레이아웃을 강제 적용
      
# 'posts' 폴더를 컬렉션으로 지정 (파일을 인식시키기 위함)
collections:
  posts:
    output: true
